version: "3.9"
services:
    postgres:
        image: postgres:13.3
        environment:
            POSTGRES_DB: "trader"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql